apiVersion: apps/v1
kind: Deployment
metadata:
  name: qpt-to-jpg-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qpt-to-jpg
  template:
    metadata:
      labels:
        app: qpt-to-jpg
    spec:
      containers:
      - image: ashwinshirva/qpt-to-jpg-service:0.0.15
        imagePullPolicy: Always
        name: qpt-to-jpg
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always

