apiVersion: v1
kind: Service
metadata:
  name: qpt-to-jpg-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: qpt-to-jpg
  type: ClusterIP
