apiVersion: v1
kind: Service
metadata:
  name: qpt-frontend-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: qpt-frontend
  type: ClusterIP
